accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import register

app_name = 'accounts'



urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/', register, name='register'),
]

article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    path('article/', views.article, name='article'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from home.views import about
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('about/', about, name='about'),
                  path('', include('shop.urls')),
                  path('', include('article.urls')),
                  path('', include('accounts.urls'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('shop/', views.shop, name='shop'),

]

article/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField(blank=True)
    image = models.ImageField(upload_to='article/%Y/%m/%d', blank=True)
    link = models.URLField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

home/models.py
from django.db import models

class HomePage(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

shop/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    link = models.URLField(blank=True)  # 링크 필드 추가
    created_at = models.DateTimeField(auto_now_add=True)
    heart = models.BooleanField(default=False)

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class RegisterForm(forms.ModelForm):
    username = forms.CharField(label='이름')
    email = forms.CharField(label='이메일')
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput)
    password2 = forms.CharField(label='비밀번호 확인', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'password2']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("비밀번호가 틀립니다.")
        return cd['password2']

accounts/views.py
from django.shortcuts import render
from .forms import RegisterForm
# Create your views here.
def register(request):
    if request.method == 'POST': # 회원가입 데이터 입력 완료 상황
        user_form = RegisterForm(request.POST) #request.POST-사용자가입력한 값
        if user_form.is_valid(): #데이터형식이맞는지 확인, validation 호출
            new_user = user_form.save(commit=False) #해당 form 모델의 인스턴스를 얻어옴
            new_user.set_password(user_form.cleaned_data['password']) #password할당
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user':new_user})
    else:
        user_form = RegisterForm()
    return render(request, 'registration/register.html', {'form':user_form})

article/views.py
from django.shortcuts import render
from .models import Article


def article(request):
    articles = Article.objects.all()
    return render(request, 'article.html', {'articles': articles})

home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html')


def about(request):
    return render(request, 'home/about.html')


def shop(request):
    return render(request, 'shop/shop.html')

def article(request):
    return render(request, 'article/article.html')


def login(request):
    return render(request, 'accounts/login.html')

shop/views.py
from .models import Category
from django.shortcuts import render
from .models import Product


def shop(request):
    categories = Category.objects.all()  # 모든 카테고리 데이터를 쿼리합니다.
    products = Product.objects.all()  # 모든 상품 데이터를 쿼리합니다.
    return render(request, 'shop.html', {'categories': categories, 'products': products})

article/templates/article.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>플래닛 패션</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">



</head>
<body>
  <header class="header sticky sticky--top js-header">
    <div class="grid">
      <nav class="navigation">
        <ul class="navigation__list navigation__list--inline">
          <li class="navigation__item"><a href="/" class="navigation__link">Home</a></li>
          <li class="navigation__item"><a href="/about/" class="navigation__link">About Us</a></li>
          <li class="navigation__item"><a href="{% url 'shop:shop' %}" class="navigation__link" >Brands</a></li>
          <li class="navigation__item"><a href="{% url 'article:article' %}" class="navigation__link navigation__link--is-active">Article</a></li>
          <li class="navigation__item"><a href="{% url 'accounts:login' %}" class="navigation__link">
            {% if user.is_authenticated %}
              <a class="navigation__link" href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
              <a class="navigation__link" href="{% url 'accounts:login' %}">Login</a>
            {% endif %}
          </a></li>
        </ul>
      </nav>
    </div>
  </header>

  <div class="article-list-container">
    {% for article in articles %}
      <div class="article-item">
        <img src="{{ article.image.url }}" alt="{{ article.title }}">
        <h3><a href="{{ article.link }}" target="_blank">{{ article.title }}</a></h3>

      </div>
    {% endfor %}
  </div>















</body>
</html>

home/templates/home/about.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>플래닛 패션</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <style>
    .name{
      margin-left: 88%;
      font-style: italic;
    }
  </style>
</head>
<body>
  <header class="header sticky sticky--top js-header">
  <div class="grid">
    <nav class="navigation">
      <ul class="navigation__list navigation__list--inline">
        <li class="navigation__item"><a href="/" class="navigation__link">Home</a></li>
        <li class="navigation__item"><a href="{% url 'home:about' %}" class="navigation__link navigation__link--is-active">About Us</a></li>
        <li class="navigation__item"><a href="{% url 'shop:shop' %}" class="navigation__link">Brands</a></li>
        <li class="navigation__item"><a href="{% url 'article:article' %}" class="navigation__link">Article</a></li>
        <li class="navigation__item"><a href="/login/" class="navigation__link">
            {% if user.is_authenticated %}
              <a class="navigation__link" href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
              <a class="navigation__link" href="{% url 'accounts:login' %}">Login</a>
            {% endif %}
        </a>
        </li>
      </ul>
    </nav>
  </div>
  </header>
  <main class="main">
    <div class="grid">
      <h1>Planet Fashion</h1>
      <p> 플래닛 패션은 지속가능한 패션 산업을 위해 노력하는 업사이클링 브랜드를 소개합니다.
      <br>환경을 사랑하고 지구를 보호하는 업사이클링 브랜드들은 패션 산업에서의 지속 가능한 변화를 이끄는데 주력하고 있습니다. 업사이클링은 우리의 핵심 가치이며, 폐기된 의류와 소재를 창의적으로 활용하여 새로운 제품을 만들어냅니다.
      <br><br>업사이클링으로 만들어진 제품들은 일상적인 패션 아이템에서 독특한 개성을 발견할 수 있습니다. 이러한 브랜드는 다양한 스타일과 트렌드를 포용하며, 동시에 환경을 생각하는 소비자들에게 의미 있는 선택을 제공합니다.
      지속 가능한 패션을 사랑하고, 환경을 함께 보호하며, 스타일과 유행을 즐기고 싶다면 우리 업사이클링 브랜드를 만나보세요. 함께 미래를 위한 패션 산업의 변화를 이끌어나갈 수 있습니다.</p>
      <p class="name">플래닛 패션</p>
    </div>
  </main>


</body>
</html>

home/templates/home/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>플래닛 패션</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <style>
        img {
            width: 760px;
            height: 393px;
        }

        .slideshow-container {
            position: relative;
            margin: auto;
        }

        .slide {
            display: none;
        }

        .slide.active {
            display: block;
        }

        .prev,
        .next {
            position: absolute;
            top: 50%;
            transform: translateY(-50%);
            font-size: 24px;
            font-weight: bold;
            padding: 8px 16px;
            color: #fff;
            cursor: pointer;
        }

        .prev {
            left: 0;
        }

        .next {
            right: 0;
            margin-right: 3px;
        }
    </style>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
        google.charts.load("current", {packages:["corechart"]});
        google.charts.setOnLoadCallback(drawChart);
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['국가', '수출액 (백만 달러)'],
                ['미국', 750],
                ['영국', 496],
                ['독일', 379],
                ['중국', 372],
                ['한국', 312]
            ]);

            var options = {
                title: '중고 의류 수출액 순위 (단위- 100만 달러)',
                pieHole: 0.4
            };

            var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
            chart.draw(data, options);
        }

        var slideIndex = 0;
        var slides = document.getElementsByClassName("slide");

        function showSlide(n) {
            if (n >= slides.length) {
                slideIndex = 0;
            } else if (n < 0) {
                slideIndex = slides.length - 1;
            }

            for (var i = 0; i < slides.length; i++) {
                slides[i].style.display = "none";
            }

            slides[slideIndex].style.display = "block";
        }

        function nextSlide() {
            slideIndex++;
            showSlide(slideIndex);
        }

        function prevSlide() {
            showSlide(slideIndex - 1);
        }

        // Show the first slide initially
        showSlide(0);
    </script>
</head>
<body>
<header class="header sticky sticky--top js-header">
    <div class="grid">
        <nav class="navigation">
            <ul class="navigation__list navigation__list--inline">
                <li class="navigation__item"><a href="/" class="navigation__link navigation__link--is-active">Home</a></li>
                <li class="navigation__item"><a href="/about/" class="navigation__link">About Us</a></li>
                <li class="navigation__item"><a href="{% url 'shop:shop' %}" class="navigation__link">Brands</a></li>
                <li class="navigation__item"><a href="{% url 'article:article' %}" class="navigation__link">Article</a></li>
                <li class="navigation__item">
                    <a href="/login/" class="navigation__link">
                        {% if user.is_authenticated %}
                        <a class="navigation__link" href="{% url 'accounts:logout' %}">Logout</a>
                        {% else %}
                        <a class="navigation__link" href="{% url 'accounts:login' %}">Login</a>
                        {% endif %}
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</header>

<main class="main">
    <div class="grid">
        <div class="slideshow-container">
            <div class="slide">
                <img src="{% static 'img/img1.jpg' %}" alt="슬라이드 1">
            </div>
            <div class="slide active">
                <img src="{% static 'img/img2.jpg' %}" alt="슬라이드 2">
            </div>

            <div class="slide">
                <img src="{% static 'img/img4.jpg' %}" alt="슬라이드 4">
            </div>

            <a class="prev" onclick="prevSlide()">&#10094;</a>
            <a class="next" onclick="nextSlide()">&#10095;</a>
        </div>

        <h2>우리가 쓰고 버린 옷은 어디로 갈까?</h2>
        <p>한국에서 더 이상 입지 않는 옷을 처리할 방법은 두 가지뿐입니다. 일반쓰레기로 배출해 소각·매립하거나, 의류수거함에 버립니다. 그러나 의류를 재사용할 거라 기대하는 의류수거함 역시 문제가 많습니다.</p>
        <div id="donutchart" style="width: 900px; height: 500px;"></div>
        <br><br>수거된 옷들의 95%가 개발도상국으로 수출됩니다. 우리나라의 헌 옷이 수출되는 국가는 인도, 캄포디아, 필리핀, 방글라데시, 파키스탄, 이라크, 인도네시아. 탄자니아, 케냐, 가나 등과 같은 개발도상국이다.
        'OEC'에 따르면 2020년 기준 한국의 헌 옷 수출량은 세계 5위로, 미국·중국·영국·독일 다음입니다. <br><br>수출된 옷 대부분은 썩지 않고 남아 심각한 환경문제를 일으킵니다. 의류폐기물 매립장 때문에 드넓은 초원에서 풀을 뜯어 먹어야 할 소들이 버려진 폐섬유를 먹고, 식수로 사용되던 아프리카 가나의 오다우강은 병을 일으키는 오염된 강이 되었습니다.
        <br><br>일반쓰레기로 배출하는 건 더 문제입니다. 배출 원단에 대한 규정조차 없습니다. 합성섬유로 이루어진 의류가 많은데, 일반쓰레기와 마찬가지로 소각합니다. 패션업계에서 사용되는 섬유 가운데 합성섬유 비중이 69%이고 의류폐기물의 70% 이상이 합성섬유입니다. 합성섬유로 이뤄진 의류들은 원재료를 분리할 방법이 없기 때문에 재활용되지 않고 대부분 매립되거나 소각됩니다. 매년 의류를 매립·소각하면서 발생되는 이산화탄소의 양은 2100만톤이 넘는 것으로 알려져 있습니다.</p>
    </div>
</main>
</body>
</html>

shop/templates/shop.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>플래닛 패션</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <style>
      .heart-icon {
        color: gray; /* 아이콘의 색상을 회색으로 설정 */
        cursor: pointer;
        margin-top: 13px;
        margin-left: 98%;
      }

      .heart-icon.filled {
        color: red; /* 클릭한 경우 하트를 채움 */
      }
    </style>

    <script>
      // JavaScript 코드
      // 페이지가 로드되었을 때 실행되는 함수
      window.addEventListener('DOMContentLoaded', function() {
        var heartIcons = document.getElementsByClassName('heart-icon');

        // 각 하트 아이콘에 클릭 이벤트를 추가
        for (var i = 0; i < heartIcons.length; i++) {
          var heartIcon = heartIcons[i];
          heartIcon.addEventListener('click', toggleHeart);
          restoreHeartState(heartIcon); // 상태 복원
        }

        // 클릭 시 하트 아이콘의 상태 변경
        function toggleHeart() {
          this.classList.toggle('filled'); // filled 클래스를 토글
          saveHeartState(this); // 상태 저장
        }

        // 상태 복원
        function restoreHeartState(heartIcon) {
          var productId = heartIcon.dataset.productId;
          var heartState = localStorage.getItem('heart-state-' + productId);
          if (heartState === 'filled') {
            heartIcon.classList.add('filled');
          }
        }

        // 상태 저장
        function saveHeartState(heartIcon) {
          var productId = heartIcon.dataset.productId;
          var heartState = heartIcon.classList.contains('filled') ? 'filled' : '';
          localStorage.setItem('heart-state-' + productId, heartState);
        }
      });
    </script>



</head>
<body>
  <header class="header sticky sticky--top js-header">
    <div class="grid">
      <nav class="navigation">
        <ul class="navigation__list navigation__list--inline">
          <li class="navigation__item"><a href="/" class="navigation__link">Home</a></li>
          <li class="navigation__item"><a href="/about/" class="navigation__link">About Us</a></li>
          <li class="navigation__item"><a href="{% url 'shop:shop' %}" class="navigation__link navigation__link--is-active">Brands</a></li>
          <li class="navigation__item"><a href="{% url 'article:article' %}" class="navigation__link">Article</a></li>
          <li class="navigation__item"><a href="{% url 'accounts:login' %}" class="navigation__link">
            {% if user.is_authenticated %}
              <a class="navigation__link" href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
              <a class="navigation__link" href="{% url 'accounts:login' %}">Login</a>
            {% endif %}
          </a></li>
        </ul>
      </nav>
    </div>
  </header>

    <div class="shop-list-container">
      {% for product in products %}
        <div class="shop-list">
          <img src="{{ product.image.url }}"> <span class="heart-icon heart-icon-{{ product.id }}" data-product-id="{{ product.id }}">&#10084;</span>
          <div>
            <h2>{{ product.name }}</h2>
            <a href="{{ product.link }}" target="_blank">바로가기&gt;&gt;</a>
            <p>{{ product.description }}</p>
          </div>

        </div>
      {% endfor %}
    </div>










</body>
</html>